name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Generate coverage report
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt
          pytest --cov=./pythonium --cov-report=xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-pythonium
          fail_ci_if_error: true 
          verbose: true 
  stlye:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort
      - name: Run flake8
        uses: julianwachholz/flake8-action@v1.1.0
        with:
          checkName: "Python Lint"
          path: pythonium
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: jamescurtin/isort-action@master
        with:
            requirementsFiles: "requirements.txt"
