name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COVERAGE_SINGLE: 60
      COVERAGE_TOTAL: 60
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: pytester-cov
        id: pytester-cov
        uses: alexanderdamiani/pytester-cov@v1.0.0
        with:
          pytest-root-dir: '.'
          cov-omit-list: 'test/*, temp/main3.py, temp/main4.py'
          cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
          cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
      - name: Comment PR on coverage total fails
        uses: thollander/actions-comment-pull-request@master
        with:
          message: ${{ steps.pytester-cov.outputs.output-table }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
