name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest isort
          pip install -r requirements.txt
  tests:
    runs-on: ubuntu-latest
    needs: build
    env:
      COVERAGE_SINGLE: 60
      COVERAGE_TOTAL: 60
    steps:
      - name: run tests
        id: tests
        run: |
          pip install coverage
          coverage run --source=pythonium -m pytest
      - name: compute coverage
        id: coverage
        run: |
          coverage report
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-pythonium
          fail_ci_if_error: true 
          verbose: true 
  stlye:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run flake8
        uses: julianwachholz/flake8-action@v1.1.0
        with:
          checkName: "Python Lint"
          path: pythonium
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: jamescurtin/isort-action@master
        with:
            requirementsFiles: "requirements.txt"
