name: Pythonium CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  play-singleplayer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Play singleplayer
        run: |
          python setup.py install
          pythonium run players pythonium.bots.standard_player
  play-multiplayer:
    runs-on: ubuntu-latest
    needs: play-singleplayer
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Play multiplayer
        run: |
          python setup.py install
          pythonium run players pythonium.bots.standard_player pythonium.bots.pacific_player
  tests:
    runs-on: ubuntu-latest
    needs: play-multiplayer
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Generate coverage report
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt
          pytest --cov=./pythonium --cov-report=xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-pythonium
          fail_ci_if_error: true
          verbose: true
  stlye:
    runs-on: ubuntu-latest
    needs: play-multiplayer
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        uses: julianwachholz/flake8-action@v1.1.0
        with:
          checkName: "Python Lint"
          path: pythonium
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  imports:
    runs-on: ubuntu-latest
    needs: play-multiplayer
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort
      - uses: jamescurtin/isort-action@master
        with:
            requirementsFiles: "requirements.txt"
            configuration: "--check-only --diff --trailing-comma --multi-line=3"
