name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest isort
          pip install -r requirements.txt
  tests:
    runs-on: ubuntu-latest
    needs: build
    env:
      COVERAGE_SINGLE: 60
      COVERAGE_TOTAL: 60
    steps:
      - uses: actions/checkout@v2
      - name: pytester-cov
        id: pytester-cov
        uses: alexanderdamiani/pytester-cov@v1.0.0
        with:
          pytest-root-dir: './pythonium'
          cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
          cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
      - name: Comment PR on coverage total fails
        uses: thollander/actions-comment-pull-request@master
        with:
          message: ${{ steps.pytester-cov.outputs.output-table }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  stlye:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run flake8
        uses: julianwachholz/flake8-action@v1.1.0
        with:
          checkName: "Python Lint"
          path: pythonium
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: jamescurtin/isort-action@master
        with:
            requirementsFiles: "requirements.txt"
